# Generated by Django 3.1 on 2020-08-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='passws',
            new_name='passwd',
        ),
    ]
